# Generated by Django 5.2.7 on 2025-10-27 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_venda_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['valor'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
