# Generated by Django 5.2.7 on 2025-10-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_alter_produto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Valor Total'),
        ),
    ]
